### ISSUE TITLE
Problems with importin

### ISSUE THREAD

**Issue by olgam4** [thisbeyond/solid-dnd#58]
I've imported the components and get this error on load.

```
GET /
file:///Users/oliviergamache/projects/hoa/node_modules/.pnpm/@thisbeyond+solid-dnd@0.7.1_solid-js@1.5.4/node_modules/@thisbeyond/solid-dnd/dist/esm/index.js:1
import { createComponent, memo, Portal, insert, effect, style, template } from 'solid-js/web';
                                                ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async nodeImport (file:///Users/oliviergamache/projects/hoa/node_modules/.pnpm/vite@3.1.2/node_modules/vite/dist/node/chunks/dep-cff57044.js:53463:21)
    at async eval (/src/islands/fvf/index.tsx:17:31)
    at async instantiateModule (file:///Users/oliviergamache/projects/hoa/node_modules/.pnpm/vite@3.1.2/node_modules/vite/dist/node/chunks/dep-cff57044.js:53392:9)
```

I'm on `solid-js@1.5.4` with version `0.7.1`.

**Comment by olgam4** [comment]
Ok, problem is with ssr: you need to add it to the `noExternal` statement.
